### ISSUE TITLE
Too many MetroFramework errors

### ISSUE THREAD

**Issue by kamalkhnl** [uiters/hotel-management-v2#6]
Hello, 
I am trying to learn the app you developed, I solved most of the errors but could not solve the MetroFramework errors.
Could you please tell me how to solve this, or could you update your source code and make it work?

I went through the MetroFramework documentation too, but couldn't quite get why the errors are being shown.

![image](https://user-images.githubusercontent.com/30455591/88487666-e616dc00-cfa6-11ea-9e42-e8cde4d8bda2.png)

![image](https://user-images.githubusercontent.com/30455591/88487705-20807900-cfa7-11ea-8593-6b587ea2d073.png)

**Comment by tvc12** [comment]
@kamalkhnl you can install [here](https://www.youtube.com/watch?v=A5bQ80jkZqE)

**Comment by tvc12** [comment]
close, because none active, you can will reopen.
